#import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "ExtraBold"

[font.bold_italic]
style = "ExtraBold Italic"

[font.italic]
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[shell]
program = "/usr/bin/fish"

[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search.matches]
foreground = 'CellBackground'
background = '#ee5396'

[colors.footer_bar]
background = '#262626'
foreground = '#ffffff'

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
