import = ["~/.config/alacritty/flow.toml"]

[env]
TERM = "screen-256color"

[window]
decorations = 'None'
dynamic_padding = false
opacity = 1.0

[font]
size = 12.5

[font.normal]
family = "Monaspace Neon"
style = "Medium"
[font.italic]
family = "Monapasce Neon"
style = "Bold Italic"
[font.bold]
family = "Monaspace Neon"
style = "Bold"
[font.bold_italic]
family = "Monaspace Neon"
style = "Bold Italic"

[shell]
program = "/usr/bin/fish"
