# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
  repeat_delay = 250
  repeat_rate = 60

  kb_layout = us
  kb_options = caps:swapescape

  follow_mouse = 1 # 0|1|2|3

  sensitivity = -1;
  accel_profile = "flat"
}
